# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
          AppBundle\Entity\User: bcrypt

    role_hierarchy:
      ROLE_ADMIN: [ ROLE_MANAGE_PRODUCT, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        our_users:
          entity: { class: AppBundle\Entity\User, property: email}

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~