parameters:
    #parameter_name: value

services:
  app.security.login_form_authenticator:
      class: AppBundle\Security\LoginFormAuthenticator
      autowire: true

  app.doctrine.hash_password_listener:
      class: AppBundle\Doctrine\HashPasswordListener
      autowire: true
      tags:
          - { name: doctrine.event_subscriber }